# Generated by Django 2.2.10 on 2020-03-02 03:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicrate', '0006_review_reviewer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'album'), ('reviewer', 'album')},
        ),
    ]
