# Generated by Django 2.2.10 on 2020-03-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrate', '0009_auto_20200301_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
