# Generated by Django 2.2.10 on 2020-03-01 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicrate', '0003_auto_20200223_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
