# Generated by Django 2.2.10 on 2020-03-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrate', '0009_auto_20200301_2201'),
    ]

    # This might be really broken...
    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='musicrate.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'album')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
